# Generated by Django 4.0.3 on 2022-05-10 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['bairro'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img')),
                ('nome_do_paciente', models.CharField(max_length=100, verbose_name='Nome do Paciente')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('01', 'Acre'), ('02', 'Alagoas'), ('03', 'Amapá'), ('04', 'Amazonas'), ('05', 'Bahia'), ('06', 'Distrito Federal'), ('07', 'Ceará'), ('08', 'Espírito Santo'), ('09', 'Goiás'), ('10', 'Maranhão'), ('11', 'Mato Grosso'), ('12', 'Mato Grosso do Sul'), ('13', 'Minas Gerais'), ('14', 'Pará'), ('15', 'Paraíba'), ('16', 'Paraná'), ('17', 'Pernambuco'), ('18', 'Piauí'), ('19', 'Rio de Janeiro'), ('20', 'Rio Grande do Norte'), ('21', 'Rio Grande do Sul'), ('22', 'Rondônia'), ('23', 'Roraima'), ('24', 'Santa Catarina'), ('25', 'Sâo Paulo'), ('26', 'Sergipe'), ('27', 'Tocantins')], default='16', max_length=2)),
                ('uf', models.CharField(choices=[('01', 'AC'), ('02', 'AL'), ('03', 'AP'), ('04', 'AM'), ('05', 'BA'), ('06', 'DF'), ('07', 'CE'), ('08', 'ES'), ('09', 'GO'), ('10', 'MA'), ('11', 'MT'), ('12', 'MS'), ('13', 'MG'), ('14', 'PA'), ('15', 'PB'), ('16', 'PR'), ('17', 'PE'), ('18', 'PI'), ('19', 'RJ'), ('20', 'RN'), ('21', 'RS'), ('22', 'RO'), ('23', 'RR'), ('24', 'SC'), ('25', 'SP'), ('26', 'SE'), ('27', 'TO')], default='16', max_length=2, verbose_name='UF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('gerero', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1, verbose_name='Gênero')),
                ('cns', models.IntegerField(unique=True, verbose_name='CNS')),
                ('ubs', models.CharField(max_length=100, verbose_name='UBS')),
                ('cipac', models.IntegerField(verbose_name='CIPAC')),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('nome_do_responsavel', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Telefone')),
                ('celular_whatsapp', models.BooleanField(default=False, verbose_name='Celular WhatsApp')),
                ('telefone_para_recado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Recado')),
                ('instituicao_de_ensino', models.CharField(blank=True, max_length=225, null=True, verbose_name='Instituição de Ensino')),
                ('diagnotico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('nivel_de_escolaridade', models.CharField(max_length=255, verbose_name='Nível de Escolaridade')),
                ('inicio_do_tratamento', models.DateField(default=datetime.date.today)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.cidade')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_do_paciente'],
            },
        ),
    ]
