# Generated by Django 4.0.3 on 2022-04-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='instituicao_de_ensino',
        ),
        migrations.AddField(
            model_name='paciente',
            name='instituicao_de_ensino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataforma.escolas'),
        ),
    ]
